server:
  port: 9001
spring:
  application:
    name: "user"
  zipkin:
    base-url: http://localhost:9411 #http://zipkin:9411
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: 4172610Guts
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    hostname: localhost
    preferIpAddress: false
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/  # http://eurekaserver:8070/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans #http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers,shutdown
  endpoint:
    health:
      show-details: always
    shutdown:
      access: unrestricted

logging:
  level:
    org:
      example:
        review: INFO

build:
  version: ${USER_VERSION:local}